### ISSUE TITLE
ouab.cls: option to include references

### ISSUE THREAD

**Issue by kaustubhad** [rbrignall/OU-SUPPS#56]
It seems that the option to add references is only for outn.cls? Might be useful if this option is also available elsewhere. In one TMA I was adding some references to papers from which the data for this TMA was taken.

By the way, it is not clear from the readme how references within the environment should be added? Is it a block of general text, and the user is free to structure any way preferred? Or in some particular way such as \item or \bibitem?

(From M140 MT).

**Comment by rbrignall** [comment]
Hi Kaustubh,
The support for displaying references is (currently) simply a box into which you can type text to refer, e.g., to pages in the course materials. Since `ouab.cls` is based on the `article` class file, you have the usual referencing features of LaTeX available to use.

I guess in principle there's no reason the features in `outn` couldn't also be in `ouab`, but they were mainly intended for tutors to refer students to relevant parts of the module texts within the solutions.
